# Importing libraries

In [35]:
import numpy as np  
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Reading data

In [36]:
data = pd.read_csv(r'C:\Users\ANKANA\Desktop\matches (1).csv')
data

id  season       city        date                        team1  \
0      1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad   
1      2    2017       Pune  2017-04-06               Mumbai Indians   
2      3    2017     Rajkot  2017-04-07                Gujarat Lions   
3      4    2017     Indore  2017-04-08       Rising Pune Supergiant   
4      5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore   
..   ...     ...        ...         ...                          ...   
631  632    2016     Raipur  2016-05-22             Delhi Daredevils   
632  633    2016  Bangalore  2016-05-24                Gujarat Lions   
633  634    2016      Delhi  2016-05-25          Sunrisers Hyderabad   
634  635    2016      Delhi  2016-05-27                Gujarat Lions   
635  636    2016  Bangalore  2016-05-29          Sunrisers Hyderabad   

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1         Rising Pune Supergiant       Rising Pune Supergiant         field   
2          Kolkata Knight Riders        Kolkata Knight Riders         field   
3                Kings XI Punjab              Kings XI Punjab         field   
4               Delhi Daredevils  Royal Challengers Bangalore           bat   
..                           ...                          ...           ...   
631  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
632  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
633        Kolkata Knight Riders        Kolkata Knight Riders         field   
634          Sunrisers Hyderabad          Sunrisers Hyderabad         field   
635  Royal Challengers Bangalore          Sunrisers Hyderabad           bat   

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35   
1    normal           0       Rising Pune Supergiant            0   
2    normal           0        Kolkata Knight Riders            0   
3    normal           0              Kings XI Punjab            0   
4    normal           0  Royal Challengers Bangalore           15   
..      ...         ...                          ...          ...   
631  normal           0  Royal Challengers Bangalore            0   
632  normal           0  Royal Challengers Bangalore            0   
633  normal           0          Sunrisers Hyderabad           22   
634  normal           0          Sunrisers Hyderabad            0   
635  normal           0          Sunrisers Hyderabad            8   

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh   
1                 7       SPD Smith   
2                10         CA Lynn   
3                 6      GJ Maxwell   
4                 0       KM Jadhav   
..              ...             ...   
631               6         V Kohli   
632               4  AB de Villiers   
633               0    MC Henriques   
634               4       DA Warner   
635               0     BCJ Cutting   

                                                venue          umpire1  \
0           Rajiv Gandhi International Stadium, Uppal      AY Dandekar   
1             Maharashtra Cricket Association Stadium   A Nand Kishore   
2              Saurashtra Cricket Association Stadium      Nitin Menon   
3                              Holkar Cricket Stadium     AK Chaudhary   
4                               M Chinnaswamy Stadium              NaN   
..                                                ...              ...   
631  Shaheed Veer Narayan Singh International Stadium   A Nand Kishore   
632                             M Chinnaswamy Stadium     AK Chaudhary   
633                                  Feroz Shah Kotla        M Erasmus   
634                                  Feroz Shah Kotla        M Erasmus   
635                             M Chinnaswamy Stadium  HDPK Dharmasena   

     

# Statistical information

In [3]:
data.describe()

id       season  dl_applied  win_by_runs  win_by_wickets  \
count  636.000000   636.000000  636.000000   636.000000      636.000000   
mean   318.500000  2012.490566    0.025157    13.682390        3.372642   
std    183.741666     2.773026    0.156726    23.908877        3.420338   
min      1.000000  2008.000000    0.000000     0.000000        0.000000   
25%    159.750000  2010.000000    0.000000     0.000000        0.000000   
50%    318.500000  2012.000000    0.000000     0.000000        4.000000   
75%    477.250000  2015.000000    0.000000    20.000000        7.000000   
max    636.000000  2017.000000    1.000000   146.000000       10.000000   

       umpire3  
count      0.0  
mean       NaN  
std        NaN  
min        NaN  
25%        NaN  
50%        NaN  
75%        NaN  
max        NaN

# Correlation between variables

In [4]:
data.corr()

id    season  dl_applied  win_by_runs  win_by_wickets  \
id              1.000000  0.471087    0.024281    -0.010263       -0.015510   
season          0.471087  1.000000    0.004170    -0.016815       -0.000708   
dl_applied      0.024281  0.004170    1.000000    -0.010893       -0.011640   
win_by_runs    -0.010263 -0.016815   -0.010893     1.000000       -0.565181   
win_by_wickets -0.015510 -0.000708   -0.011640    -0.565181        1.000000   
umpire3              NaN       NaN         NaN          NaN             NaN   

                umpire3  
id                  NaN  
season              NaN  
dl_applied          NaN  
win_by_runs         NaN  
win_by_wickets      NaN  
umpire3             NaN

# Data processing

# Checking duplicate values

In [5]:
data.duplicated().any()

False

# Checking null values

In [6]:
data.isnull().sum().sort_values(ascending=False)

umpire3            636
city                 7
player_of_match      3
winner               3
umpire1              1
umpire2              1
toss_winner          0
season               0
date                 0
team1                0
team2                0
result               0
toss_decision        0
dl_applied           0
win_by_runs          0
win_by_wickets       0
venue                0
id                   0
dtype: int64

# Dropping columns which play no role in prediction analysis

In [7]:
df_1 = data.drop(['id', 'date', 'result', 'dl_applied', 'player_of_match', 'venue',
'umpire1', 'umpire2','season'], axis = 1)
df_1

city                        team1                        team2  \
0    Hyderabad          Sunrisers Hyderabad  Royal Challengers Bangalore   
1         Pune               Mumbai Indians       Rising Pune Supergiant   
2       Rajkot                Gujarat Lions        Kolkata Knight Riders   
3       Indore       Rising Pune Supergiant              Kings XI Punjab   
4    Bangalore  Royal Challengers Bangalore             Delhi Daredevils   
..         ...                          ...                          ...   
631     Raipur             Delhi Daredevils  Royal Challengers Bangalore   
632  Bangalore                Gujarat Lions  Royal Challengers Bangalore   
633      Delhi          Sunrisers Hyderabad        Kolkata Knight Riders   
634      Delhi                Gujarat Lions          Sunrisers Hyderabad   
635  Bangalore          Sunrisers Hyderabad  Royal Challengers Bangalore   

                     toss_winner toss_decision                       winner  \
0    Royal Challengers Bangalore         field          Sunrisers Hyderabad   
1         Rising Pune Supergiant         field       Rising Pune Supergiant   
2          Kolkata Knight Riders         field        Kolkata Knight Riders   
3                Kings XI Punjab         field              Kings XI Punjab   
4    Royal Challengers Bangalore           bat  Royal Challengers Bangalore   
..                           ...           ...                          ...   
631  Royal Challengers Bangalore         field  Royal Challengers Bangalore   
632  Royal Challengers Bangalore         field  Royal Challengers Bangalore   
633        Kolkata Knight Riders         field          Sunrisers Hyderabad   
634          Sunrisers Hyderabad         field          Sunrisers Hyderabad   
635          Sunrisers Hyderabad           bat          Sunrisers Hyderabad   

     win_by_runs  win_by_wickets  umpire3  
0             35               0      NaN  
1              0               7      NaN  
2              0              10      NaN  
3              0               6      NaN  
4             15               0      NaN  
..           ...             ...      ...  
631            0               6      NaN  
632            0               4      NaN  
633           22               0      NaN  
634            0               4      NaN  
635            8               0      NaN  

[636 rows x 9 columns]

In [8]:
df_1.isnull().sum().sort_values(ascending = False)

umpire3           636
city                7
winner              3
win_by_wickets      0
win_by_runs         0
toss_decision       0
toss_winner         0
team2               0
team1               0
dtype: int64

# Dropping column 'umpire3' because it consists of only null values

In [9]:
df_1.drop(['umpire3'], inplace = True, axis = 1)

# Replacing null values

In [10]:
#determining mode
df_1['city'].value_counts()

Mumbai            85
Bangalore         66
Kolkata           61
Delhi             60
Hyderabad         49
Chennai           48
Chandigarh        46
Jaipur            33
Pune              32
Durban            15
Ahmedabad         12
Centurion         12
Visakhapatnam     11
Rajkot            10
Dharamsala         9
Johannesburg       8
Cape Town          7
Cuttack            7
Ranchi             7
Port Elizabeth     7
Abu Dhabi          7
Raipur             6
Sharjah            6
Indore             5
Kochi              5
Kanpur             4
East London        3
Kimberley          3
Nagpur             3
Bloemfontein       2
Name: city, dtype: int64

In [11]:
df_1['winner']=df_1['winner'].fillna('Mumbai Indians')

In [12]:
df_1['city']=df_1['city'].fillna('Dubai')

In [13]:
#null values have been removed
df_1.isnull().sum().sort_values(ascending = False)

win_by_wickets    0
win_by_runs       0
winner            0
toss_decision     0
toss_winner       0
team2             0
team1             0
city              0
dtype: int64

In [14]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   city            636 non-null    object
 1   team1           636 non-null    object
 2   team2           636 non-null    object
 3   toss_winner     636 non-null    object
 4   toss_decision   636 non-null    object
 5   winner          636 non-null    object
 6   win_by_runs     636 non-null    int64 
 7   win_by_wickets  636 non-null    int64 
dtypes: int64(2), object(6)
memory usage: 39.9+ KB


In [15]:
#importing labelEncoder
from sklearn import preprocessing
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
# Encode labels in column 'species'. 
df_1['city']= label_encoder.fit_transform(df_1['city']) 
df_1['team1']=label_encoder.fit_transform(df_1['team1']) 
df_1['team2']=label_encoder.fit_transform(df_1['team2']) 
df_1['winner']=label_encoder.fit_transform(df_1['winner']) 
df_1['toss_winner']=label_encoder.fit_transform(df_1['winner']) 
df_1['toss_decision']=label_encoder.fit_transform(df_1['winner']) 

# Data modeling

In [208]:
from sklearn.model_selection import train_test_split

In [245]:
#X and Y # Iteration
X = df_1.drop(['win_by_wickets','win_by_runs','toss_winner', 'toss_decision'], axis=1)
y = df_1['winner']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=40)

In [246]:
from sklearn import ensemble
clf_rand = ensemble.RandomForestClassifier()
from sklearn.linear_model import LogisticRegression 
clf_log = LogisticRegression(random_state = 0)  
from sklearn.tree import DecisionTreeClassifier
clf_dectree = DecisionTreeClassifier()
from sklearn.naive_bayes import GaussianNB
clf_gnb = GaussianNB()
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=5)
from sklearn.model_selection import train_test_split

In [247]:
clf_rand.fit(X_train, y_train)
clf_log.fit(X_train, y_train)
clf_dectree.fit(X_train,y_train)
clf_gnb.fit(X_train, y_train)
clf_knn.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


KNeighborsClassifier()

# Decision tree on train data

In [248]:
from sklearn.tree import DecisionTreeClassifier

clf_dtc = DecisionTreeClassifier
clf_dectree.fit(X_train,y_train)
y_prediction_dectree = clf_dectree.predict(X_test)
accuracy_score_dectree = clf_dectree.score(X_train, y_train)*100
print (accuracy_score_dectree)


100.0


# Logistic model on train data

In [249]:
from sklearn.linear_model import LogisticRegression 

clf_log = LogisticRegression(random_state = 0) 
clf_log.fit(X_train,y_train)
y_prediction_log = clf_dectree.predict(X_train)
accuracy_score_log = clf_log.score(X_train, y_train)*100
print (accuracy_score_log)


59.325842696629216


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# KNN on train data

In [266]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=5)
clf_knn.fit(X_train,y_train)
y_prediction_knn = clf_knn.predict(X_train)
accuracy_score_knn = clf_knn.score(X_train, y_train)*100
print (accuracy_score_knn)


74.38202247191012


# Random Forest on train data

In [265]:
from sklearn.ensemble import RandomForestClassifier

clf_rfc = RandomForestClassifier(n_estimators = 100)
clf_rfc.fit(X_train, y_train)
y_prediction_rfc = clf_rfc.predict(X_test)
accuracy_score_rfc = clf_rfc.score(X_train, y_train)*100
print (accuracy_score_rfc)


100.0


# Gaussian NB on train data

In [250]:
from sklearn.naive_bayes import GaussianNB
clf_gnb = GaussianNB()
clf_gnb.fit(X_train, y_train)
y_prediction_gnb = clf_gnb.predict(X_test)
accuracy_score_gnb = clf_gnb.score(X_train, y_train)*100
print (accuracy_score_gnb)

100.0


# Confusion matrices

In [252]:
pred_log = clf_log.predict(X_test)
pred_gnb = clf_gnb.predict(X_test)
pred_rand = clf_rand.predict(X_test)
pred_dectree = clf_dectree.predict(X_test)
pred_knn = clf_knn.predict(X_test)

In [253]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, pred_log)
print(cm1)

[[25  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  6  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  2 13  0  4  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0 15  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  9  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  9  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  1  6  0  2  0  0  1  0]
 [ 0  0  0  0  0  0  0  7  0  6  0  0  5  0]
 [ 0  0  0  0  0  0  0  2  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  1  0  1  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  7  2]]


In [255]:
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y_test, pred_knn)
print(cm3)

[[22  1  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 7  1  4  0  0  0  0  0  0  0  0  0  0  0]
 [ 6  0 10  0  3  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0 13  1  4  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0 10  3  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  9 12  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  0 11  0  0  2  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  1  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  0  0  0  0  3  0  0 14  7]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  3  6]]


In [256]:
from sklearn.metrics import confusion_matrix
cm4 = confusion_matrix(y_test, pred_rand)
print(cm4)

[[25  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 21  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  6  4  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 18  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  1  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 24  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  9]]


In [257]:
from sklearn.metrics import confusion_matrix
cm5 = confusion_matrix(y_test, pred_dectree)
print(cm5)

[[25  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 21  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 18  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 24  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  9]]


In [264]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, pred_gnb)
print(cm2)

[[25  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 21  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 18  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 24  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  9]]


# Logistic regression on test data

In [258]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred_log)*100
print (accuracy_score_log)

59.325842696629216


# KNN on Test Data

In [260]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=3)
clf_knn.fit(X_train, y_train)
y_prediction_gnb = clf_knn.predict(X_test)
accuracy_score_knn = clf_knn.score(X_train, y_train)*100
print (accuracy_score_knn)

81.12359550561797


# Random Forest on test data

In [261]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred_rand)*100

95.81151832460732

# Decision tree on test data

In [262]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred_dectree)*100

100.0

# Gaussian NB on Test Data

In [263]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred_gnb)*100
print (accuracy_score_gnb)

100.0


# Random Forest performs the best